blogpost + image for #jetzt2 rückblick
chaos-jetzt/website_pelican pull request #34
Opened 2023-08-08 18:33 UTC by scammo

If two people approve please merge. Thanks

2023-08-08 18:43 UTC, e1mo commented on content/articles/jetzt2-rueckblick.md
> +![Kreidemalerei bei der GPN]({static}/images/dezentrale-tuer.jpg)
Das eventuell nochmal nach Landscape beschneiden? Hochkant zieht das ziemlich viel Platz.

2023-08-08 18:47 UTC, scammo commented on content/articles/jetzt2-rueckblick.md
> +![Kreidemalerei bei der GPN]({static}/images/dezentrale-tuer.jpg)
done

2023-08-08 18:52 UTC, e1mo commented on content/images/dezentrale-tuer (2).jpg:Zone.Identifier
Die Datei müsste noch gelöscht werden :sweat_smile:
Kann ich aber auch mit machen, wenn ich die Bilder vorm publishen nochmal komprimiere.

2023-08-08 19:17 UTC, scammo commented on content/images/dezentrale-tuer (2).jpg:Zone.Identifier
done

2023-08-08 21:16 UTC, rugk approved these changes
Wollen wir noch nen Disclaimer hinzufügen, dass das teilweise mit ChatGPT generiert wurde, wie:
> (Disclaimer: Dieser Text wurde teilweise mit ChatGPT generiert.)

2023-08-08 21:16 UTC, rugk commented on content/articles/jetzt2-rueckblick.md
> +Das Geekend bot eine Vielzahl von Aktivitäten für die Teilnehmenden. Neben einem interessanten "Ask me Anything"-Segment, in dem Fragen rund um die Themen Chaos, Politik und Technologie beantwortet w
```suggestion
Das Geekend bot eine Vielzahl von Aktivitäten für die Teilnehmenden. Neben einem interessanten „Ask me Anything”-Segment, in dem Fragen rund um die Themen Chaos, Politik und Technologie beantwortet wurden, gab es auch verschiedene Hands-on-Workshops. Einige Teilnehmende beschäftigten sich mit dem Thema „nix(OS)”, während andere den neuen „chaos.jetzt Offboarding Prozess” diskutierten. Die Entwickler*innen unter den Geekend-Teilnehmer*innen lernten „test-driven development” näher kennen und bauten mit Begeisterung JavaScript-Bots. Außerdem wurde das Wiki gepflegt und eine IoT-Überwachungskamera erfolgreich in Betrieb genommen.
```

real quotes

2023-08-09 15:39 UTC, rugk approved these changes

2023-08-10 08:57 UTC, supermomme approved these changes

2023-08-11 17:15 UTC, rugk requested changes
Leider grammarnazi hier🙈

2023-08-11 17:15 UTC, rugk commented on content/articles/jetzt2-rueckblick.md
> +Den restlichen Tag über gab es nebst veganem Chilli auch Treffen mit dem Ziel Wissen über die Organisation von Geekends zu sichern aber auch unser [Wiki] auf einen aktuellen Stand zu bringen.
```suggestion
Den restlichen Tag über gab es nebst veganem Chilli auch Treffen, die das Ziel hatten, Wissen pber die Organisation von Geekends zu sichern. Ganz nebenbei brachten sie unser [Wiki] auf einen aktuellen Stand.
```

2023-08-11 17:15 UTC, rugk commented on content/articles/jetzt2-rueckblick.md
> +Zudem konnten wir uns unter dem Motto "betreutes Hacken" an den Sicherheitslücken einer IoT-Kamera austoben.
```suggestion
Zudem konnten wir uns unter dem Motto „betreutes Hacken“ an den Sicherheitslücken einer IoT-Kamera austoben.
```

2023-08-11 17:15 UTC, rugk commented on content/articles/jetzt2-rueckblick.md
> +Während des gesamten Wochenende war die Versorgung mit Essen und Getränken gesichert. Neben Pizza und Chilli zum Mittag und Abendesse, stellten wir auch ein komplett vegetarisches / veganes ewiges Fr
```suggestion
Während des gesamten Wochenendes war die Versorgung mit Essen und Getränken gesichert. Neben Pizza und Chilli zum Mittag und Abendessen, stellten wir auch ein komplett vegetarisches / veganes ewiges Frühstück auf die Beine.
```

Genetiv

2023-08-11 17:15 UTC, rugk commented on content/articles/jetzt2-rueckblick.md
> +Zwischen Frühstück und Abschlussplenum am Sonntag haben wir wichtigen Input für die Frage "Wer sind und was wollen wir?" gesammelt.
```suggestion
Zwischen Frühstück und Abschlussplenum am Sonntag haben wir wichtigen Input zur Frage „Wer sind und was wollen wir?“ gesammelt.
```

2023-08-11 17:15 UTC, rugk commented on content/articles/jetzt2-rueckblick.md
> +Wir hoffen das alle Teilnehmenden eine gute Heimreise hatte und freuen uns darauf, möglichst viele auf dem nächsten Geekend wieder zu sehen. Ein herzliches Dankeschön an alle Beteiligten, die dieses
```suggestion
Wir hoffen, dass alle Teilnehmenden eine gute Heimreise hatte und freuen uns darauf, möglichst viele auf dem nächsten Geekend wieder zu sehen. Ein herzliches Dankeschön an alle Beteiligten, die dieses Geekend zu einem unvergesslichen Erlebnis gemacht haben!
```

Man kann ja nicht "dieses" einsetzen.

2023-08-11 17:15 UTC, rugk commented on content/articles/jetzt2-rueckblick.md
> +Authors: scammo, crowd, e1mo
Keine headline mehr? Da stand wsd von wichtig für preview von Mastodon?

2023-08-11 20:25 UTC, merged